require('plugins.feline')
require('plugins.mini')
require('plugins.nvim-treesitter')

vim.schedule(function()
    require('plugins.guess-indent')
    require('plugins.nvim-lspconfig')
    require('plugins.which-key')
    require('plugins.gitsigns')
    require('plugins.crates')
end)
