require('which-key').setup({
    preset = 'modern',
    delay = 0,
    icons = {
        mappings = false,
        -- :h key-notation
        keys = {
            Up = "<Up>",
            Down = "<Down>",
            Left = "<Left>",
            Right = "<Right>",
            C = "<Ctrl>",
            M = "<Alt>",
            D = "<Super>",
            S = "<Shift>",
            CR = "<CR>",
            Esc = "<Esc>",
            ScrollWheelDown = "<WheelDown>",
            ScrollWheelUp = "<WheelUp>",
            NL = "<NL>",
            BS = "<BS>",
            Space = "<Space>",
            Tab = "<Tab>",
            F1 = "<F1>",
            F2 = "<F2>",
            F3 = "<F3>",
            F4 = "<F4>",
            F5 = "<F5>",
            F6 = "<F6>",
            F7 = "<F7>",
            F8 = "<F8>",
            F9 = "<F9>",
            F10 = "<F10>",
            F11 = "<F11>",
            F12 = "<F12>",
        },
    },
})
