theme = "dark_plus_no_background"

[editor]
auto-format = false
lsp.display-inlay-hints = true
rulers = [81, 101]

[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[editor.statusline]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
